### ISSUE TITLE
[BUG] Navigation failed because browser has disconnected error for certain websites

### ISSUE THREAD

**Issue by neekey** [alixaxel/chrome-aws-lambda#104]
Hi Just want to share an issue I found that bothered me for a while, which might have something to do with the compiled chromium version 80.

## Environment
* `chrome-aws-lambda` Version: 2.1.2
* `puppeteer` / `puppeteer-core` Version: 2.1.x
* OS: Linux
* Node.js Version: 12.x
* Lambda / GCF Runtime: Linux2

## Expected Behavior

Puppeteer should be able to open website when using `goTo()`

## Current Behavior

For certain websites, failed to open pages, it threw errors of `Navigation failed because browser has disconnected`, the affected websites that I found:

- dailymotion.com
- https://www.arabnews.com/
- https://www.sayidaty.net/
- https://uae.sharafdg.com/

But it works normal when testing in my local which is using chromium from module puppeteer.

**Comment by neekey** [comment]
My solution for anyone experiencing the same problem:

fix the chromium version to 79 by fix the module versions to :

- `chrome-aws-lambda`: `2.0.x`
- `puppeteer-core`: `2.0.x`
- `puppeteer`: `2.0.x`

**Comment by oakgary** [comment]
> My solution for anyone experiencing the same problem:
> 
> fix the chromium version to 79 by fix the module versions to :
> 
> * `chrome-aws-lambda`: `2.0.x`
> * `puppeteer-core`: `2.0.x`
> * `puppeteer`: `2.0.x`

thank you for saving me the headache 

i was using chrome-aws-lambda with latest versions as well and ran into the same problem
using the 2.0.x versions fixed the problem of navigation crashes

**Comment by nathan1uphealth** [comment]
This also worked for me! Thanks for this

**Comment by bschelling** [comment]
Could you elaborate a little? How exactly do your package.json entries look like? Are you adding puppeteer to your node_modules too? I'm having exactly the same issue...

**Comment by bschelling** [comment]
Just in case someone else gets confused:

```
"dependencies": {
    "chrome-aws-lambda": "2.0.x",
    "puppeteer-core": "2.0.x"
  }
```


did the trick for me too. thanks!

**Comment by pgreda** [comment]
Same issue here. It can be reporduced by accessing https://filmweb.pl
Rollback resolved the problem.

**Comment by tnolet** [comment]
We are updating to Puppeteer 2.1 on Lambda and found the same issue. We can also reproduce it perfectly with the following site:

https://toogoodtogo.nl

Also can report that the https://www.arabnews.com/ site mentioned by @neekey has exactly the same behaviour

**Comment by Josh-ES** [comment]
Same issue on my end. We store HTML in a directory and start an express server within the Lambda pointing to it, then navigating the browser to that server. I can rollback to 2.0.x to resolve the problem.

**Comment by 14gasher** [comment]
I just tried rolling back to 2.0.x for both puppeteer-core and chrome-aws-lambda, but I'm still getting the disconnect. Did any other flags need to be turned on / off?

**Comment by Josh-ES** [comment]
@14gasher I'm running with the following args:

```
import chromium from 'chrome-aws-lambda'
...
await chromium.puppeteer.launch({
    args: [
        ...chromium.args,
        '--single-process',
    ],
})
```

**Comment by alixaxel** [comment]
@neekey Sorry it took a bit to follow up on this.

In all of these cases, the browser always crashes with:

> [0405/032327.939344:FATAL:service.cc(56)] Check failed: !base::SystemMonitor::Get().

Related issues:

- https://github.com/puppeteer/puppeteer/issues/5487
- https://github.com/alixaxel/chrome-aws-lambda/issues/3#issuecomment-595825598
- https://github.com/alixaxel/chrome-aws-lambda/issues/39#issuecomment-589244053

What seems to be happening is Chromium is relying on additional processes for decoding audio/video, and since Lambda is single-threaded it ends up crashing. I'll see what can be done to overcome this.

In all these cases, it seems to be related to audio and/or video being played on the page:

---

#### https://www.dailymotion.com/

Caused by [dmp.main.e0d00292a4faa658874d.es5.js](https://static1.dmcdn.net/playerv5/dmp.main.e0d00292a4faa658874d.es5.js) which plays the videos on the site.

![image](https://user-images.githubusercontent.com/262782/78466071-146d6480-76f5-11ea-9cb3-81188a2f9b76.png)

---

#### https://www.arabnews.com/

The issue seems caused by [sca.17.4.114.js](https://static.adsafeprotected.com/sca.17.4.114.js), which uses the WebAudio API to fingerprint the device.

![image](https://user-images.githubusercontent.com/262782/78465974-184cb700-76f4-11ea-8de5-b3ad965faee9.png)

---

#### https://www.sayidaty.net/

Also caused by [sca.17.4.114.js](https://static.adsafeprotected.com/sca.17.4.114.js).

---

#### https://uae.sharafdg.com/

Caused by [notif.mp3](https://assetscdn-wchat.freshchat.com/static/assets/audio/notif.mp3).

---

#### https://www.filmweb.pl/

@pgreda Caused by [765260af-5da5-4c5f-94ad-c2f0f5db7182.mp4](https://d76w6nzzdeq7h.cloudfront.net/assets/765e614e-b462-44fe-822c-f5bd10fa3a8c/20200327/765260af-5da5-4c5f-94ad-c2f0f5db7182.mp4).

---

#### https://toogoodtogo.nl/

Caused by [life-of-bread.mp4](https://toogoodtogo.nl/images/placeholders/front-page/v2/life-of-bread.mp4) / [life-of-bread.webm](https://toogoodtogo.nl/images/placeholders/front-page/v2/life-of-bread.webm).

**Comment by bschelling** [comment]
What about discarding media requests as a workaround? Something along the lines of 

```JavaScript 
await page.setRequestInterception(true);
page.on('request', (req) => {
   if (req.resourceType() === 'Media') {
      req.abort();
   }
   else {
      req.continue();
   }
}

**Comment by jongear** [comment]
Adding an abort on image and media requests allowed my lambda to complete successfully. 

```js
await page.setRequestInterception(true);

page.on('request', async(request) => {
  const requestType = request.resourceType();

  if (requestType === 'image' || requestType === 'media') {
    return request.abort();
  }

  return request.continue();
});
```

**Comment by gsouf** [comment]
Please, note that I opened a ticket on chromium support https://bugs.chromium.org/p/chromium/issues/detail?id=1060099#c6

**Comment by alexfernandez** [comment]
Recently found this issue again, workaround is to remove `--single-process` from the args passed:

```
    const args = chromium.args
    args.splice(args.indexOf('--single-process'), 1)
    return await chromium.puppeteer.launch({
        args,
        ...
    })
```

Unfortunately this doesn't work on AWS Lambda, the browser does never start. @alixaxel Do you know of any way to make it work without `--single-process`? Thanks!

**Comment by silveur** [comment]
Seems like `AudioService init bug at --single-process mod` was solved on Chromium 25 days ago

**Comment by alexfernandez** [comment]
> Seems like `AudioService init bug at --single-process mod` was solved on Chromium 25 days ago

@silveur I suppose we will have to wait for 3.0 to include the fix?

**Comment by gsouf** [comment]
@alixaxel do you think you could package latest version of chromium with chrome-aws-lambda so that we can test if it solves.

If you don't have time, can you explain how to do it please?

**Comment by zachlevy** [comment]
> Adding an abort on image and media requests allowed my lambda to complete successfully.
> 
> ```js
> await page.setRequestInterception(true);
> 
> page.on('request', async(request) => {
>   const requestType = request.resourceType();
> 
>   if (requestType === 'image' || requestType === 'media') {
>     return request.abort();
>   }
> 
>   return request.continue();
> });
> ```

my workaround was to also ignore all javascript files. Luckily I didn't need any of them
```
requestType === 'script'
```

**Comment by andreikrasnou** [comment]
I have the same issue with https://www.jetblue.com/travel-agents/travel-agent-waiver-codes website. 
As far as I can see there are no media types which are requested.  @neekey  am i right that the only way now to solve it in single process mode is package downgrade?

**Comment by alixaxel** [comment]
@gsouf Spent the entire day around this, adding the following option to `args` seems to solve it:

```
--disable-features=AudioServiceOutOfProcess
```

![image](https://user-images.githubusercontent.com/262782/81445265-6e3bd100-9170-11ea-82b6-e4f4bbd3a3dd.png)

Tested on 81.0.4044.0 (which will be published today hopefully).

**Comment by daveroberts** [comment]
Glad to see you're okay!

**Comment by gsouf** [comment]
@alixaxel you're the boss thanks!

Also I don't know if you noticed, an internal fix should come in chrome 83

**Comment by netdotter787** [comment]
This is issue is still coming up.


  "status": "failed",
    "error": "Navigation failed because browser has disconnected!",
    "context": {
        "callbackWaitsForEmptyEventLoop": true,
        "functionVersion": "$LATEST",

`try {

    let chromeArgs = chromium.args;
    chromeArgs.push('--disable-features=AudioServiceOutOfProcess');
    chromeArgs.push('--disable-features=AudioServiceOutOfProcessKillAtHang');    
    chromeArgs.push('--disable-software-rasterizer');
    chromeArgs.push('--disable-gpu');

    browser = await chromium.puppeteer.launch({
      args: chromeArgs,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true
    });

    //Create 
    const page = await browser.newPage();
    await page.setUserAgent(event.user_agent);
    await page.setViewport({width: event.view_port.width, height: event.view_port.height, deviceScaleFactor: 1});
    
    await page.goto(event.screen_shot_url);
    

    //const image = await page.screenshot();
    //await Tooling.toS3(Tooling.getPushConfig(image, event.bucket, `image/png`, event.destination, Tooling.s3FileAcl))

    result = await page.title();
  } catch (e) {
    console.log(e);
    console.log('Failed')
    return failed(e, context)
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }`

**Comment by AlexisNava** [comment]
Hi!!

I have the same issue.

## Environment

- **chrome-aws-lambda**: ^5.5.0
- **puppeteer-core**: ^5.5.0
- **OS**: Linux
- **Node**: nodejs12.x
- **Lambda**: Linux2

I include some code, I hope it would helpful

### serverless.yml

```yml
service: generate-file

plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-plugin-git-variables

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 1536
  timeout: 30
  tracing: true
  stage: ${self:custom.stacks.${self:custom.stack}.stage, "dev"}
  region: ${self:custom.stacks.${self:custom.stack}.region, "us-east-1"}
  profile: ${self:custom.stacks.${self:custom.stack}.profile, "default"}
  layers: ${file(config/config.yml):${self:provider.stage}.layers}
  vpc: ${self:custom.stacks.${self:custom.stack}.vpc}
  environment: ${file(config/environment.yml):${self:provider.stage}.environment}
  iamRoleStatements: ${file(config/iam.yml):${self:provider.stage}.iamRoleStatements}
  tags:
    branch: ${git:branch}
    commit: ${git:sha1}
    version: ${git:describeLight}
  apiKeys:
    - ApiKey-${self:service}-${self:provider.stage}

functions:
  generate_pdf:
    description: Generate PDF files from a HTML template.
    handler: src/handlers/generatePDF/handler.handler

resources: ${file(config/resources.yml):${self:provider.stage}.resources}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  stack: ${opt:stack, "dev"}
  stacks: ${file(config/stacks.yml):stacks}
  prefix: ${self:custom.stacks.${self:custom.stack}.prefix}
  scheduleEnabled:
    production: true
    dev: false
  warmup:
    events:
      schedule: 'rate(5 minutes)'
    timeout: 20
    prewarm: true
    enabled: production
    memorySize: 512
    role: ${self:custom.stacks.${self:custom.stack}.warmupRole}
  exportGitVariables: false
```

### generatePDF.ts

```typescript
function getHTML(templateContent: string, templateName: string) {
  const templateFile = FileSystem.readFileSync(
    `./src/templates/${templateName}/index.hbs`,
    'utf8',
  );
  const template = Handlerbars.compile(templateFile);

  return template(templateContent);
}

export default async function (
  bucketName: string,
  fileName: string,
  templateContent: string,
  templateName: string,
  s3: S3,
) {
  let browser = null;

  try {
    const executablePath = await Chromium.executablePath;

    browser = await Chromium.puppeteer.launch({
      args: ['--disable-features=AudioServiceOutOfProcess', ...Chromium.args],
      defaultViewport: Chromium.defaultViewport,
      executablePath,
      headless: Chromium.headless,
    });

    const browserPage = await browser.newPage();

    browserPage.setContent(getHTML(templateContent, templateName));

    const pdf = await browserPage.pdf({
      format: 'A4',
      printBackground: true,
    });

    s3Upload(bucketName, fileName, pdf, s3);
  } catch (error) {
    console.error(error);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}
```

## Expected Behavior

Puppeteer should be able to generate the PDF file

## Current Behavior

The process raises this error

```json
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: Navigation failed because browser has disconnected!",
    "reason": {
        "errorType": "Error",
        "errorMessage": "Navigation failed because browser has disconnected!",
        "stack": [
            "Error: Navigation failed because browser has disconnected!",
            "    at /var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147",
            "    at /var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:62",
            "    at Array.map (<anonymous>)",
            "    at Object.emit (/var/task/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:51:43)",
            "    at CDPSession.emit (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)",
            "    at CDPSession._onClosed (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:247:14)",
            "    at Connection._onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:128:21)",
            "    at WebSocket.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:17:30)",
            "    at WebSocket.onClose (/var/task/node_modules/ws/lib/event-target.js:136:16)",
            "    at WebSocket.emit (events.js:314:20)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: Navigation failed because browser has disconnected!",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```
