### ISSUE TITLE
[BUG] no such file or directory, mkdir '/home/sbx_user1051/.fonts'

### ISSUE THREAD

**Issue by stevenspiel** [alixaxel/chrome-aws-lambda#131]
## Environment
* `chrome-aws-lambda` Version: 3.0.4
* `puppeteer` / `puppeteer-core` Version: 3.0.4
* OS:  Mac
* Node.js Version:  14.x
* Lambda / GCF Runtime:  12.x
* Running with `sam invoke` and docker

## Expected Behavior
Fonts should download when running:

```js
await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf')
```

(taken from [here](https://github.com/alixaxel/chrome-aws-lambda/tree/1cad533e64168a125f6003acbfebfdf42c920dec#fonts))

## Current Behavior
An error is returned:

```
ERROR	Invoke Error 	{
  "errorType":"Error",
  "errorMessage":"ENOENT: no such file or directory, mkdir '/home/sbx_user1051/.fonts'",
  "code":"ENOENT",
  "errno":-2,
  "syscall":"mkdir",
  "path":"/home/sbx_user1051/.fonts",
  "stack":["Error: ENOENT: no such file or directory, mkdir '/home/sbx_user1051/.fonts'",
  "    at mkdirSync (fs.js:841:3)",
  "    at Function.font (/var/task/node_modules/chrome-aws-lambda/source/index.js:33:7)",
  "    at Runtime.exports.handler (/var/task/index.js:15:18)",
  "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]
}
```

## Steps to Reproduce

test.js:

```js
const chromium = require('chrome-aws-lambda');

exports.handler = async (event, context, callback) => {
  let result = null;
  let browser = null;

  // when the following line is commented out, the function runs without error.
  await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf');

  try {
    browser = await chromium.puppeteer.launch({
      args: chromium.args,
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath,
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });

    let page = await browser.newPage();

    await page.goto(event.url || 'https://example.com');

    result = await page.title();
  } catch (error) {
    return callback(error);
  } finally {
    if (browser !== null) {
      await browser.close();
    }
  }

  return callback(null, result);
};
```

template.yaml:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  test:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: test.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 60
      Layers:
          - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:10
```

package.json:

```json
{
  "description": "client side ejs compiled with express middleware",
  "main": "app.js",
  "name": "test-font-chrome-aws-lambda",
  "version": "1.0.1",
  "dependencies": {
    "aws-sdk": "2.498.0",
    "chrome-aws-lambda": "^3.0.4",
    "puppeteer-core": "^3.0.4"
  }
}
```
