### ISSUE TITLE
[BUG] Error on running locally using `now dev`

### ISSUE THREAD

**Issue by solancer** [alixaxel/chrome-aws-lambda#135]
Unable to run chrome-aws-lambda with `now` on  Mac. The workaround in docs about adding puppeteer to devDependencies triggering the use of puppeteer instead of puppeteer-core breaks with now dev because it compiles the lambda and its dependencies into a single file using NCC. 

## Environment
* `chrome-aws-lambda` Version:
* `puppeteer` / `puppeteer-core` Version:
* OS: Mac
* Node.js Version: v12.16.1
* Lambda / GCF Runtime: v12.16.1

## Current Behavior
Failed to launch the browser process!
/tmp/chromium: /tmp/chromium: cannot execute binary file

**Comment by alixaxel** [comment]
Refer to https://github.com/alixaxel/chrome-aws-lambda#running-locally

**Comment by alixaxel** [comment]
Apologies, I wrongly closed this issue. I will look into this tomorrow.

**Comment by JonathanHelvey** [comment]
Hi, I am having a similar issue.  My deployed function through Lambda works fine.  However, using Serverless offline I get that same error. Just curious if there was a fix?  Thank you!

```
Error grabbing gas data Error: Failed to launch the browser process!
/var/folders/8d/4f252mzd4hlcfbrl5n2v1_bh0000gn/T/chromium: /var/folders/8d/4f252mzd4hlcfbrl5n2v1_bh0000gn/T/chromium: cannot execute binary file
```

**Comment by alixaxel** [comment]
@solancer With the new `vercel dev` (version 19.1.0) I couldn't replicate the issue on a Mac.

Everything works as expected, so perhaps the problem only applies to `now`?

**Comment by alixaxel** [comment]
@JonathanHelvey Could you share your `serverless.yml` file? Also:

- What OS are you using? Mac or Linux?
- Did you install `puppeteer` or just `puppeteer-core`?

I tried this on Linux and I couldn't reproduce the error you got.

**Comment by JonathanHelvey** [comment]
@alixaxel I am using Mac and I only installed puppeteer-core.

serverless.yml file below.

```
service: backend-fuel-friend-finder-api

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 2048 # recommended
  timeout: 30 # optional, in seconds, default is 6
  layers:
    - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:10

 plugins:
   - serverless-offline

functions:
  getData:
    handler: getData.handler
    events:
      - http:
          path: gasData
          method: get
          cors: true
    environment:
      S3_REGION: us-east-1

```

I have everything up and running online and my small project is finished,  so this is not a big deal, but I was just noticing serverless offline does not work for me. Thanks for the reply and help!
