### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by josejorgers** [alixaxel/chrome-aws-lambda#168]
## Environment
* `chrome-aws-lambda` Version:2.0.2
* `puppeteer-core` Version:2.0.0
* OS: Windows 10
* Node.js Version: 14.x 
* Lambda / GCF Runtime: `nodejs12.x`

## Expected Behavior
I have made a toy example using ```chrome-aws-lambda``` where it should navigate to ```https://www.google.com``` and retrieve the page title

## Current Behavior

When running ```sam local invoke``` it gets stuck mounting the runtime container. I'm not even able to shutdown the process pressing ```Ctrl + C```.

When deployed to AWS through ```sam deploy``` and tested, it gives the following error:

```text
{
  "errorType": "Runtime.UnhandledPromiseRejection",
  "errorMessage": "Error: Navigation failed because browser has disconnected!",
  "trace": [
    "Runtime.UnhandledPromiseRejection: Error: Navigation failed because browser has disconnected!",
    "    at process.<anonymous> (/var/runtime/index.js:35:15)",
    "    at process.emit (events.js:315:20)",
    "    at processPromiseRejections (internal/process/promises.js:209:33)",
    "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
  ]
}
```

## Steps to Reproduce
This is my ```template.yaml```

```yaml
# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  a11ytool

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  PuppeteerTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/testHandler.handler
      Runtime: nodejs12.x
      MemorySize: 2048
      Timeout: 900
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
```

Here is my handler ```src/handlers/testHandler.js```
```js

const chromium = require('chrome-aws-lambda');

let browser = null

let page = null


exports.handler = async (event, context, callback) => {
    let result = null

    try{
        browser = await chromium.puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath,
            headless: chromium.headless,
            ignoreHTTPSErrors: true
        })

        page = await browser.newPage()

        page.goto('https://www.google.com', {waitUntil: ['domcontentloaded', 'networkidle2']})

        await page.waitForSelector('title')
        
        result = await page.title()

    }
    catch(err){
        console.log(err);
        callback(err)
    }
    finally{
        if (page) await page.close()
        if (browser) await browser.disconnect()
    }

    return callback(null, result);
}
```
Any suggestion? Thanks beforehand.
