### ISSUE TITLE
fonts.conf file doesn't seem to be read when trying to disable anti-aliasing and font hinting

### ISSUE THREAD

**Issue by qboot** [alixaxel/chrome-aws-lambda#176]
Hi! I'm completely new to the serverless world and I'm trying to set up correctly my first lambda with puppeteer.
Everything is working as expected. Kudos for this repo and how you maintain it 🙏 .

My issue is that I'm trying to disable all (system wide) fonts options: `anti-aliasing`, `hinting`, etc. with a `fonts.conf` file but it doesn't seem to work. My goal is to have a "pixel-perfect" screenshot.

I'm using the latest layer for my runtime (nodejs12.x) provided by [shelfio](https://github.com/shelfio/chrome-aws-lambda-layer), like that:

```yml 
provider:
  name: aws
  layers:
    # https://github.com/shelfio/chrome-aws-lambda-layer
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:20
  # function parameters
  runtime: nodejs12.x
[...]
functions:
  run:
    handler: handler.run
    environment:
      FONTCONFIG_PATH: /var/task/fonts
```

And I've added a specific directory `fonts` in the lambda root code containing:
- a font `Verdana.ttf`
- a `fonts.conf` file: 

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/var/task/fonts/</dir>
  <match target="font">
    <edit name="rgba" mode="assign"><const>rgb</const></edit>
    <edit name="hinting" mode="assign"><bool>false</bool></edit>
    <edit name="antialias" mode="assign"><bool>false</bool></edit>
    <edit name="autohint" mode="assign"><bool>false</bool></edit>
    <edit name="hintstyle" mode="assign"><const>hintnone</const></edit>
    <edit name="lcdfilter" mode="assign"><const>lcdnone</const></edit>
  </match>
  <config></config>
</fontconfig>
```

Plus, I've added the `FONTCONFIG_PATH: /var/task/fonts` env var in the `serverless.yml` file.
Verdana font is working well 👍 . But the screenshot still appear blurry. I've tested locally with the same `fonts.conf` file in Docker, and the screenshot is perfect, like I want.

The browser is instantiated like that:
```js
const chromium = require('chrome-aws-lambda');
[...]
const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath,
    defaultViewport: { width: 400, height: 300 },
});
````
Do you have any clue on why my `fonts.conf` is "partially read"? Or maybe something is overriding it in the runtime context of a lambda? Thanks!
