### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by roshansourav** [alixaxel/chrome-aws-lambda#211]
# **cannot find module** .webpack/service/puppeteer/lib/browser

**Comment by BungeeDesign** [comment]
I had this issue when running locally using the [serverless-bundle](https://github.com/AnomalyInnovations/serverless-bundle#readme) plugin. I managed to fix this by using the force exclude option in the `serverless.yml` config. I also installed puppeteer as a dev dependency, as I'm using the Lambda Layer for puppeteer/chrome.

```yml
custom:
  bundle:
    forceExclude:
      - chrome-aws-lambda
```
