### ISSUE TITLE
Included build has screenshot problems

### ISSUE THREAD

**Issue by WesPainter** [alixaxel/chrome-aws-lambda#47]
I first noticed after I deployed to lambda (using the layer generated from the commands in the docs) that my screenshots were blank at the bottom.  Here is what it should look like vs what it looked like using a different chromium build of the same version: 

Included Chromium             |  Rebuilt Chromium
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/19840248/59777162-1f4c2b00-9282-11e9-83fe-7eaf2d77afbb.png)  |  ![image](https://user-images.githubusercontent.com/19840248/59777126-0d6a8800-9282-11e9-9450-8e23aec8fc0a.png)

So I used this script at https://github.com/pahud/lambda-layer-headless-chromium to build the same version (linux dev 76.0.3786.0), compressed it, and overwrote the build included with this layer. Works okay now. Not sure what about the build is different or if it matters, but thought I would file an issue in case.

To reproduce, deploy the code attached at the bottom.  Then attach the lambda layer generated from this repo.

To see the correct version, replace the chrome build in the layer with one built from https://github.com/pahud/lambda-layer-headless-chromium

serverless.yml
```yaml
service: screenshot-problem-sample

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 1600
  timeout: 30

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/** # exclude puppeteer chrome if exists

functions:
  screenshot:
    handler: handler.screenshot
    events:
    - http:
        method: get
        path: screenshot

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "image/png"
```
handler.js
```node
const chromium = require('chrome-aws-lambda');

module.exports.screenshot = async(event) => {
  const browser = await chromium.puppeteer.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
    defaultViewport: { height: 900, width: 1440, }
  });

  const page = await browser.newPage();
  await page.goto('https://make.plated.com/home?utm_ad=50Px2', { waitUntil: 'networkidle0' });

  const $ele = await page.$('body');
  const { _, height } = await $ele.boundingBox();

  const capture = await page.screenshot({
    fullPage: false,
    encoding: 'base64',
    clip: {
      x: 0,
      y: 0,
      width: 1440,
      height: height
    },
  });

  await browser.close();

  return {
    statusCode: 200,
    body: capture,
    headers: {
      'Content-Type': 'image/png',
    },
    isBase64Encoded: true,
  };
};
```

package.json
```json
{
  "name": "cal-repro",
  "version": "1.0.0",
  "description": "Reproduce screenshot issue.",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Wes Painter",
  "license": "ISC",
  "devDependencies": {
    "chrome-aws-lambda": "^1.17.1"
  },
  "dependencies": {
    "serverless": "^1.45.1"
  }
}
```
