### ISSUE TITLE
[BUG] Error on AWS, cannot find chromium.br file

### ISSUE THREAD

**Issue by kamilkp** [alixaxel/chrome-aws-lambda#67]
Trying to get a basic example to work on AWS lambda and here's the error I get: Seems like chromium is not installed on the OS there?

## Environment
* `chrome-aws-lambda` Version: 1.20.3
* `puppeteer` / `puppeteer-core` Version: 1.20.0
* OS: AWS Lambda
* Node.js Version: 10.x
* Lambda / GCF Runtime: ?

## Expected Behavior
Should work

## Current Behavior
Error: ENOENT: no such file or directory, open 'node_modules/chrome-aws-lambda/source/../bin/chromium.br'

**Comment by alixaxel** [comment]
This shouldn't happen... Are you doing something special with your Lambda deployment?
Could you share code and/or steps to reproduce?

![image](https://user-images.githubusercontent.com/262782/67210703-740ad880-f411-11e9-97da-cc7b600e9fa6.png)

If you attach the deployment package of your Lambda it would be much easier to debug.

**Comment by kamilkp** [comment]
well I just deploy it with `serverless`. This is it's code:


```javascript
import chromium from 'chrome-aws-lambda';
import puppeteer from 'puppeteer-core';

export default async function print({
  url
}) {
  let browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless,
  });

  const page = await browser.newPage();

  await page.goto(url, {
    waitUntil: ['networkidle0', 'load', 'domcontentloaded'],
  });

  const result = await page.pdf({
    printBackground: true,
    format: 'A4',
    displayHeaderFooter: false,
  });

  return result.data;
}
```

Here is a portion of my serverless.yml file:

```yml
service: sling-lambda-print-2

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    DEBUG: false
    LOGGING: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource: "arn:aws:s3:::${self:custom.bucket}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"

plugins:
  - serverless-webpack

custom:
  chrome:
    flags:
      - --hide-scrollbars
    functions:
      - render
  bucket: headless-print-files

functions:
  render:
    description: Render pdf
    memorySize: 2536
    timeout: 300 # AWS Lambda limitation
    handler: src/handlers/render.default
    environment:
      DEBUG: false
      BUCKET: ${self:custom.bucket}
      FONTCONFIG_PATH: /var/task/fonts

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

```

**Comment by alixaxel** [comment]
@kamilkp I can't provide support for serverless, you should open a issue with them, I suspect that `serverless-webpack` might be the culprit, but without the deployment package I can't be sure.

Also not sure where this configuration is original from, but I don't think you should be setting `FONTCONFIG_PATH` and I also don't think `--hide-scrollbars` has any effect with just the code you shared. Closing this as it doesn't seem to be an issue with this project but rather something else.

**Comment by kamilkp** [comment]
In case someone finds this issue in the future here's what I did to solve it:

1. Add `chrome-aws-lamdba` as an `external` in webpack config:

```javascript
externals: ['aws-sdk', 'chrome-aws-lambda'],
```

2. Upload the chrome-aws-lambda `layer` as an AWS Lambda Layer via AWS console according to these instructions: https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer

3. Specify in `serverless.yml` which function should use this layer:

```yml
funcitons:
    your_function:
        layers:
            layers:
                - arn:aws:lambda:<region>:<id>:layer:<name of layer>:<revision>
```

**Comment by kamilkp** [comment]
@alixaxel might be worth adding this to your readme maybe? ^

**Comment by shellscape** [comment]
@alixaxel I second the suggestion from @kamilkp to add the note about `externals` to the instructions.

**Comment by mithundas79** [comment]
> ```js
> 'chrome-aws-lambda'
> ```

I am following this instruction with the following with the framework version 1.78.1 and serverless-webpack@latest

When I overide my externals variables in webpack.config.js as shown above, I get following error on deploy
```
ERROR in ./node_modules/handlebars/lib/index.js
Module not found: Error: Can't resolve '../dist/cjs/handlebars' in '/home/mithun/Workspace/boltinsight-lambdas/htmltopdf_service/node_modules/handlebars/lib'
 @ ./node_modules/handlebars/lib/index.js 7:17-50
 @ ./handler.ts

ERROR in ./node_modules/handlebars/lib/index.js
Module not found: Error: Can't resolve '../dist/cjs/handlebars/compiler/printer' in '/home/mithun/Workspace/boltinsight-lambdas/htmltopdf_service/node_modules/handlebars/lib'

```
So I keep externals as ```externals: [nodeExternals()] ```
and in serverless.yml file I do following
```
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - chrome-aws-lambda
```
This makes sure the chrome-aws-lambda module is not bundle... however when i deploy and run the code I get
**Access Denied**
