### ISSUE TITLE
[BUG] Permission error on local devlopment

### ISSUE THREAD

**Issue by Spy-Seth** [alixaxel/chrome-aws-lambda#72]
First off all thanks for this wonderful repository! It's helps us a lot to use Chrome in a lambda to take WebGL application screenshot 👍 

## Environment
* `chrome-aws-lambda` Version: v2.0.0
* `puppeteer-core` Version: v2.0.0
* OS: macOS Mojave v10.14.5
* Node.js Version: v10.16.3
* Lambda / GCF Runtime: nodejs10.x

## Expected Behavior
When running the lambda localy with `serverless offline` feature, I'm expecting to puppeteer to be able to launch chromium.

## Current Behavior

I use the given command to run locally the lambda:

```
$ AWS_LAMBDA_FUNCTION_NAME="configuration-screenshot-dev-local" serverless offline --port=4000
```

And when I access to it throw HTTP the lambda crash and I get the a permission error in the console:

```
/var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium: /var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium: cannot execute binary file


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

Error: Failed to launch chrome!
/var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium: /var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium: cannot execute binary file


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/path/to/my/app/ConfigurationScreenshootLambda/node_modules/puppeteer-core/lib/Launcher.js:348:14)
    at Interface.helper.addEventListener (/path/to/my/app/ConfigurationScreenshootLambda/node_modules/puppeteer-core/lib/Launcher.js:337:50)
    at Interface.emit (events.js:203:15)
    at Interface.EventEmitter.emit (domain.js:448:20)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Here some of my `chromium`  executable informations: 
```
$ ls -alh /var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium
-rwx------  1 armand  staff   129M Oct 30 11:10 /var/folders/64/ft1wgkts2sx3krql2cvx0klw0000gn/T/chromium
```

I try to add execution right for everyone `chmod a+x /.../chromium` to test it change something but the permission error persist

Everything works perfectly in the AWS environment.

## Possible Solution
No idea sorry

## Steps to Reproduce

My serverless stack:

```yaml
service: configuration-screenshot

provider:
  name: aws
  profile: default
  runtime: nodejs10.x
  stage: dev
  region: eu-west-3

plugins:
  - serverless-offline

package:
  exclude:
    # Ensure that we do not upload any Google Chrome execurable. We use an AWS Lambda layer that provide it.
    - node_modules/chrome-aws-lambda/**
    - node_modules/puppeteer/.local-chromium/**

functions:
  screenshot:
    handler: handler.screenshot
    layers:
      # See https://github.com/shelfio/chrome-aws-lambda-layer
      - arn:aws:lambda:eu-west-3:764866452798:layer:chrome-aws-lambda:6
    memorySize: 2048
    timeout: 30
    events:
      - http:
          method: get
          path: screenshot
          contentHandling: CONVERT_TO_BINARY

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - '*/*'
```

My package.json:
```json
{
  "name": "@custhome/configuration-screenshot",
  "version": "1.0.0",
  "main": "handler.js",
  "author": "Custhome team <dev@custhome.app>",
  "private": true,
  "scripts": {
    "dev": "AWS_LAMBDA_FUNCTION_NAME=\"configuration-screenshot-dev-local\" serverless offline --port=4000",
    "deploy": "serverless deploy"
  },
  "dependencies": {
    "data-urls": "^1.1.0",
    "strip-scripts": "^0.9.0"
  },
  "devDependencies": {
    "chrome-aws-lambda": "^2.0.0",
    "puppeteer-core": "^2.0.0",
    "serverless": "^1.55.1",
    "serverless-offline": "^5.12.0"
  }
}
```
