### ISSUE TITLE
[BUG] Chrome not launching during npm test in lambda pre-build phase

### ISSUE THREAD

**Issue by nechemiaseif** [alixaxel/chrome-aws-lambda#78]
Hi!

Hi I'm having some issues getting Chrome to launch during the Build phase in my CodePipeline. I'm running some mocha unit tests that use the chrome-aws-lambda and puppeteer-core libraries. When I skip the tests and go straight to deployment, the package works just as it's supposed to -- no problem there.

The error message I get differs, depending on whether or not I include the full puppeteer package in my package.json's devDependencies, which already indicates that the pre-build environment differs from lambda's (see below for more on that). 

When I only include chrome-aws-lambda and puppeteer-core, I get the following error: 

`Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"`

When I also include the full puppeteer library in devDependencies, I get:

```
Error: Error: Failed to launch chrome! 
/codebuild/output/src626568390/src/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory 
```

Following your logging instructions in  #37 , I checked some environment variables/routes, and this is what I found.

Values during the pre-build phase (where it's not working):
 
```
AWS_EXECUTION_ENV: AWS_ECS_EC2 
FONTCONFIG_PATH: undefined 
LD_LIBRARY_PATH: undefined 
/tmp/aws/lib: false
```

Values during actual lambda execution (where it is working):

```
AWS_EXECUTION_ENV: AWS_Lambda_nodejs10.x
FONTCONFIG_PATH: /tmp/aws
LD_LIBRARY_PATH: /tmp/aws/lib:/var/lang/lib:/lib64:/usr/lib64:/var/runtime:/var/runtime/lib:/var/task:/var/task/lib:/opt/lib
/tmp/aws/lib: true
```

Just for reference the buildspec.yml file I'm using starts with the following specifications. It's during the pre_build -> npm test phase that it actually tries to launch Chrome and fails:

```
phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install
      - npm install dotenv

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - npm test
```

As mentioned above, everything works fine in actual execution, and it's also working fine when I test locally (using the full puppeteer package, as mentioned in your Wiki). However, this environment seems to differ from both. 

Any ideas?

Thank you!
