### ISSUE TITLE
How to use the AWS lambda layer

### ISSUE THREAD

**Issue by tnolet** [alixaxel/chrome-aws-lambda#9]
Hi, just an idea. Maybe add an example on how to use the uploaded layer in a piece of lambda code?

**Comment by alixaxel** [comment]
@tnolet After generating the well-formed Layer according to [instructions](https://github.com/alixaxel/chrome-aws-lambda#aws-lambda-layer), you just need to upload the `chrome-aws-lambda.zip` file as a new Layer and simply attach it to your Lambda definition.

The code remains exactly the same, the only thing that you **shouldn't** do if you follow the layer approach is:

```shell
npm i chrome-aws-lambda
```

I hope that helps!

**Comment by eyaylagul** [comment]
hello, i'm a newbie for aws-lambda. i follow the instructions for aws-lambda.

project structure
- lib
- -  chrome-aws-lambda-1.11.2.tgz
- node_modules
- - chrome-aws-lambda
- handler.js (i use your example code for a test)
- package.json
- serverless.yml


serverless.yml
```yml
...
package:
  exclude:
  - lib/**

layers:
  libNodeModule:
    path: lib
    description: "additional node_module"
functions:
  hello:
    handler: handler.hello
    layers:
      - {Ref: LibNodeModuleLambdaLayer}
```
before i call
```
sls invoke local -f hello
```

the code return

```javascript
{
    "code": "MODULE_NOT_FOUND"
}
```

how i can solve the problem?

Thank You.
